;;; multihost-connection-test.el --- Persistent worker regressions -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'multihost-connection)

(defmacro multihost-connection-test--isolated (&rest body)
  (declare (indent 0) (debug t))
  `(let* ((multihost-state-directory (make-temp-file "multihost-pool-test-" t))
          (multihost-worker-init-file (expand-file-name "init.el" multihost-state-directory))
          (multihost-connection-limit 2)
          (multihost-connection-idle-timeout 60)
          (multihost-connection--workers nil)
          (multihost-connection--queue nil)
          (multihost-connection--pump-timer nil))
     (with-temp-file multihost-worker-init-file
       (prin1 '(setq multihost-worker-operation-functions
                     '((test . (lambda (payload directory)
                                 (when (plist-get payload :prompt) (read-passwd "Password: "))
                                 (when (plist-get payload :crash) (kill-emacs 23))
                                 (when (plist-get payload :marker)
                                   (with-temp-buffer
                                     (insert "executed\n")
                                     (append-to-file (point-min) (point-max) (plist-get payload :marker))))
                                 (when (plist-get payload :gate)
                                   (while (not (file-exists-p (plist-get payload :gate))) (sleep-for 0.02)))
                                 (when (plist-get payload :fault)
                                   (let* ((request (multihost-worker--read-json "request.json"))
                                          (worker (file-name-nondirectory (directory-file-name default-directory)))
                                          (id (gethash "id" request)))
                                     (pcase (plist-get payload :fault)
                                       ('wrong-worker (multihost-worker--notify "wrong-worker" "result" id))
                                       ('wrong-id (multihost-worker--notify worker "result" "wrong-id"))
                                       ('oversized-line (princ (concat (make-string 70000 ?X) "\n")))
                                       ('malformed (princ "MULTIHOST-RPC/1 {bad json\n")))
                                     nil))
                                 (list :status 'succeeded :value (list directory (plist-get payload :value)))))))
              (current-buffer)))
     (set-file-modes multihost-worker-init-file #o600)
     (unwind-protect (progn ,@body)
       (multihost-connection-reset)
       (when (timerp multihost-connection--pump-timer) (cancel-timer multihost-connection--pump-timer))
       (delete-directory multihost-state-directory t))))

(defun multihost-connection-test--wait (request &optional predicate)
  (let ((deadline (+ (float-time) 10))
        (predicate (or predicate (lambda (request)
                                   (memq (multihost-request-status request) multihost-connection--terminal)))))
    (while (and (not (funcall predicate request)) (< (float-time) deadline))
      (accept-process-output nil 0.02))
    (should (funcall predicate request))
    request))

(ert-deftest multihost-connection-reuses-worker-and-keeps-cwd-per-request ()
  (multihost-connection-test--isolated
    (let* ((one (multihost-connection-submit "/ssh:ops@web#2222:/first/" 'test '(:value "one") nil))
           (_ (multihost-connection-test--wait one))
           (two (multihost-connection-submit "/ssh:ops@web#2222:/second/" 'test '(:value "two") nil)))
      (multihost-connection-test--wait two)
      (should (eq (multihost-request-status one) 'succeeded))
      (should (eq (multihost-request-status two) 'succeeded))
      (should (eq (multihost-request-process one) (multihost-request-process two)))
      (should (equal (plist-get (multihost-request-result two) :value) '("/ssh:ops@web#2222:/second/" "two")))
      (should (= (plist-get (car (multihost-connection-snapshots)) :completed) 2)))))

(defun multihost-connection-test--touch (file)
  (with-temp-file file (insert "released")))

(ert-deftest multihost-connection-queued-cancel-keeps-active-request-and-calls-once ()
  (multihost-connection-test--isolated
    (let* ((gate (expand-file-name "gate" multihost-state-directory))
           (marker (expand-file-name "marker" multihost-state-directory)) counts
           (active (multihost-connection-submit "/ssh:web:/" 'test (list :gate gate :marker marker)
                                                (lambda (_request result) (push (plist-get result :status) counts))))
           (queued (multihost-connection-submit "/ssh:web:/other/" 'test '(:value "cancelled")
                                                (lambda (_request result) (push (plist-get result :status) counts)))))
      (multihost-connection-test--wait active (lambda (_) (file-exists-p marker)))
      (should (eq (multihost-request-status queued) 'queued))
      (multihost-connection-cancel queued)
      (multihost-connection-cancel queued)
      (should (process-live-p (multihost-request-process active)))
      (multihost-connection-test--touch gate)
      (multihost-connection-test--wait active)
      (should (equal (sort counts #'string<) '(cancelled succeeded)))
      (should (= (plist-get (car (multihost-connection-snapshots)) :completed) 1)))))

(ert-deftest multihost-connection-active-cancel-discards-worker-without-replay ()
  (multihost-connection-test--isolated
    (let* ((gate (expand-file-name "gate" multihost-state-directory))
           (marker (expand-file-name "marker" multihost-state-directory)) (callbacks 0)
           (active (multihost-connection-submit "/ssh:web:/" 'test (list :gate gate :marker marker)
                                                (lambda (&rest _) (cl-incf callbacks)))))
      (multihost-connection-test--wait active (lambda (_) (file-exists-p marker)))
      (multihost-connection-cancel active)
      (multihost-connection-cancel active)
      (should (= callbacks 1))
      (should-not (process-live-p (multihost-request-process active)))
      (let ((next (multihost-connection-submit "/ssh:web:/" 'test '(:value "next") nil)))
        (multihost-connection-test--wait next)
        (should (eq (multihost-request-status next) 'succeeded))
        (should-not (eq (multihost-request-process active) (multihost-request-process next))))
      (with-temp-buffer (insert-file-contents marker) (should (equal (buffer-string) "executed\n"))))))

(ert-deftest multihost-connection-timeout-includes-queue-without-cancelling-other-work ()
  (multihost-connection-test--isolated
    (let* ((gate (expand-file-name "gate" multihost-state-directory))
           (marker (expand-file-name "marker" multihost-state-directory))
           (active (multihost-connection-submit "/ssh:web:/" 'test (list :gate gate :marker marker) nil))
           (queued (multihost-connection-submit "/ssh:web:/" 'test nil nil :timeout 1)))
      (multihost-connection-test--wait active (lambda (_) (file-exists-p marker)))
      (multihost-connection-test--wait queued)
      (should (eq (multihost-request-status queued) 'timed-out))
      (should-not (multihost-request-process queued))
      (should (process-live-p (multihost-request-process active)))
      (multihost-connection-test--touch gate)
      (multihost-connection-test--wait active)
      (should (eq (multihost-request-status active) 'succeeded)))))

(ert-deftest multihost-connection-active-timeout-retires-worker ()
  (multihost-connection-test--isolated
    ;; Warm up locally so the deadline tests running execution, not CI startup.
    (multihost-connection-test--wait (multihost-connection-submit "/ssh:web:/" 'test nil nil))
    (let* ((gate (expand-file-name "gate" multihost-state-directory))
           (marker (expand-file-name "marker" multihost-state-directory)) (callbacks 0)
           (request (multihost-connection-submit "/ssh:web:/" 'test (list :gate gate :marker marker)
                                                 (lambda (&rest _) (cl-incf callbacks)) :timeout 1)))
      (multihost-connection-test--wait request (lambda (_) (file-exists-p marker)))
      (multihost-connection-test--wait request)
      (should (eq (multihost-request-status request) 'timed-out))
      (should (= callbacks 1))
      (should-not (process-live-p (multihost-request-process request)))
      (should-not (multihost-connection-snapshots)))))

(ert-deftest multihost-connection-global-limit-and-per-host-order ()
  (multihost-connection-test--isolated
    (let* ((gate (expand-file-name "gate" multihost-state-directory))
           (one-marker (expand-file-name "one" multihost-state-directory))
           (two-marker (expand-file-name "two" multihost-state-directory))
           (one (multihost-connection-submit "/ssh:web:/" 'test (list :gate gate :marker one-marker) nil))
           (same-host (multihost-connection-submit "/ssh:web:/second/" 'test nil nil))
           (two (multihost-connection-submit "/ssh:db:/" 'test (list :gate gate :marker two-marker) nil))
           (third (multihost-connection-submit "/ssh:other:/" 'test nil nil)))
      (multihost-connection-test--wait one (lambda (_) (and (file-exists-p one-marker) (file-exists-p two-marker))))
      (should (= (length (multihost-connection-snapshots)) 2))
      (should (eq (multihost-request-status same-host) 'queued))
      (should (eq (multihost-request-status third) 'queued))
      (multihost-connection-test--touch gate)
      (mapc #'multihost-connection-test--wait (list one same-host two third))
      (should (>= (multihost-request-started-at same-host) (multihost-request-ended-at one)))
      (should (cl-every (lambda (request) (eq (multihost-request-status request) 'succeeded))
                        (list one same-host two third)))
      (should (<= (length (multihost-connection-snapshots)) 2)))))

(ert-deftest multihost-connection-idle-eviction-and-ttl ()
  (multihost-connection-test--isolated
    (let* ((multihost-connection-limit 1)
           (first (multihost-connection-submit "/ssh:web:/" 'test nil nil)))
      (multihost-connection-test--wait first)
      (let ((second (multihost-connection-submit "/ssh:db:/" 'test nil nil)))
        (multihost-connection-test--wait second)
        (should (eq (multihost-request-status second) 'succeeded))
        (should-not (process-live-p (multihost-request-process first)))
        (let ((multihost-connection-idle-timeout 0.05)
              (third (multihost-connection-submit "/ssh:db:/" 'test nil nil)))
          (multihost-connection-test--wait third)
          (multihost-connection-test--wait third (lambda (_) (null (multihost-connection-snapshots))))
          (should-not (process-live-p (multihost-request-process second))))))))

(ert-deftest multihost-connection-reset-is-targeted-and-calls-queued-observers ()
  (multihost-connection-test--isolated
    (let* ((gate (expand-file-name "gate" multihost-state-directory))
           (marker (expand-file-name "marker" multihost-state-directory)) (count 0)
           (active (multihost-connection-submit "/ssh:web:/" 'test (list :gate gate :marker marker)
                                                (lambda (&rest _) (cl-incf count))))
           (queued (multihost-connection-submit "/ssh:web:/" 'test nil (lambda (&rest _) (cl-incf count))))
           (other (multihost-connection-submit "/ssh:db:/" 'test nil nil)))
      (multihost-connection-test--wait active (lambda (_) (file-exists-p marker)))
      (multihost-connection-test--wait other)
      (multihost-connection-reset "/ssh:web:/unrelated-cwd/")
      (should (= count 2))
      (should (eq (multihost-request-status active) 'cancelled))
      (should (eq (multihost-request-status queued) 'cancelled))
      (should (process-live-p (multihost-request-process other)))
      (should (equal (mapcar (lambda (x) (plist-get x :directory)) (multihost-connection-snapshots)) '("/ssh:db:"))))))

(ert-deftest multihost-connection-init-change-invalidates-queued-and-idle-workers ()
  (multihost-connection-test--isolated
    (let* ((gate (expand-file-name "gate" multihost-state-directory))
           (marker (expand-file-name "marker" multihost-state-directory))
           (first (multihost-connection-submit "/ssh:web:/" 'test (list :gate gate :marker marker) nil))
           (queued (multihost-connection-submit "/ssh:web:/" 'test nil nil)))
      (multihost-connection-test--wait first (lambda (_) (file-exists-p marker)))
      (with-temp-buffer (insert "\n;; changed trusted configuration\n")
                        (append-to-file (point-min) (point-max) multihost-worker-init-file))
      (multihost-connection-test--touch gate)
      (multihost-connection-test--wait first)
      (multihost-connection-test--wait queued)
      (should (eq (multihost-request-status queued) 'failed))
      (should (string-match-p "init changed" (plist-get (multihost-request-result queued) :error)))
      (let ((next (multihost-connection-submit "/ssh:web:/" 'test nil nil)))
        (multihost-connection-test--wait next)
        (should (eq (multihost-request-status next) 'succeeded))
        (should-not (eq (multihost-request-process first) (multihost-request-process next)))))))

(ert-deftest multihost-connection-background-auth-prompt-fails-without-consuming-rpc ()
  (multihost-connection-test--isolated
    (let ((request (multihost-connection-submit "/ssh:web:/" 'test '(:prompt t) nil)))
      (multihost-connection-test--wait request)
      (should (eq (multihost-request-status request) 'failed))
      (should (string-match-p "requires interaction" (plist-get (multihost-request-result request) :error)))
      (should-not (process-live-p (multihost-request-process request)))
      (let ((next (multihost-connection-submit "/ssh:web:/" 'test nil nil)))
        (multihost-connection-test--wait next)
        (should (eq (multihost-request-status next) 'succeeded))))))

(ert-deftest multihost-connection-crash-does-not-replay-and-queue-recovers ()
  (multihost-connection-test--isolated
    (let* ((first (multihost-connection-submit "/ssh:web:/" 'test '(:crash t) nil))
           (next (multihost-connection-submit "/ssh:web:/" 'test nil nil)))
      (multihost-connection-test--wait first)
      (multihost-connection-test--wait next)
      (should (eq (multihost-request-status first) 'failed))
      (should (string-match-p "exited 23" (plist-get (multihost-request-result first) :error)))
      (should (eq (multihost-request-status next) 'succeeded))
      (should-not (eq (multihost-request-process first) (multihost-request-process next))))))

(ert-deftest multihost-connection-protocol-faults-retire-workers-exactly-once ()
  (multihost-connection-test--isolated
    (dolist (fault '(wrong-worker wrong-id malformed oversized-line))
      (let* ((count 0)
             (request (multihost-connection-submit "/ssh:web:/" 'test (list :fault fault)
                                                  (lambda (&rest _) (cl-incf count)))))
        (multihost-connection-test--wait request)
        (should (eq (multihost-request-status request) 'failed))
        (should (= count 1))
        (should-not (process-live-p (multihost-request-process request)))
        (should-not (multihost-connection-snapshots))))))

(ert-deftest multihost-connection-local-config-validation-performs-no-remote-io ()
  (multihost-connection-test--isolated
    (dolist (setting '(state init program relative-program relative-state))
      (let ((multihost-state-directory multihost-state-directory)
            (multihost-worker-init-file multihost-worker-init-file)
            (multihost-worker-program multihost-worker-program)
            (default-directory default-directory))
        (pcase setting
          ('state (setq multihost-state-directory "/ssh:secret:/state/"))
          ('init (setq multihost-worker-init-file "/ssh:secret:/init.el"))
          ('program (setq multihost-worker-program "/ssh:secret:/emacs"))
          ('relative-program (setq multihost-worker-program "./emacs" default-directory "/ssh:secret:/"))
          ('relative-state (setq multihost-state-directory "state" default-directory "/ssh:secret:/")))
        (cl-letf (((symbol-function 'file-readable-p) (lambda (&rest _) (ert-fail "Configuration caused I/O")))
                  ((symbol-function 'executable-find) (lambda (&rest _) (ert-fail "Configuration caused executable search")))
                  ((symbol-function 'make-directory) (lambda (&rest _) (ert-fail "Configuration caused directory I/O"))))
          (should-error (multihost-connection-submit "/ssh:web:/" 'test nil nil) :type 'user-error))))))

(ert-deftest multihost-connection-identity-keeps-user-hop-port-and-state ()
  (multihost-connection-test--isolated
    (let ((keys (mapcar #'multihost-connection--key
                       '("/ssh:ops@web#2222:/a/" "/ssh:root@web#2222:/a/"
                         "/ssh:ops@web#22:/a/" "/ssh:jump|ssh:ops@web#2222:/a/"))))
      (should (= (length (delete-dups (copy-tree keys))) 4))
      (should (equal (car keys) (multihost-connection--key "/ssh:ops@web#2222:/b/")))
      (let ((multihost-state-directory (expand-file-name "other" multihost-state-directory)))
        (should-not (equal (car keys) (multihost-connection--key "/ssh:ops@web#2222:/a/")))))))

(ert-deftest multihost-connection-payload-snapshot-and-private-files ()
  (multihost-connection-test--isolated
    (let* ((secret (copy-sequence "TOP_SECRET"))
           (request (multihost-connection-submit "/ssh:web:/" 'test (list :value secret) nil)))
      (aset secret 0 ?X)
      (multihost-connection-test--wait request)
      (should (equal (cadr (plist-get (multihost-request-result request) :value)) "TOP_SECRET"))
      (should-not (string-match-p "TOP_SECRET" (prin1-to-string (multihost-connection-snapshots))))
      (let ((storage (multihost-connection-worker-storage (multihost-request-worker request))))
        (should (= (logand (file-modes storage) #o777) #o700))
        (dolist (name '("request.json" "result.json" "bootstrap.json"))
          (should-not (file-exists-p (expand-file-name name storage))))))))

(ert-deftest multihost-connection-observer-can-submit-during-spawn-failure ()
  (multihost-connection-test--isolated
    (let ((program multihost-worker-program) next)
      (let* ((multihost-worker-program "/nonexistent/multihost-emacs")
             (request (multihost-connection-submit
                       "/ssh:web:/" 'test nil
                       (lambda (&rest _)
                         (let ((multihost-worker-program program))
                           (setq next (multihost-connection-submit "/ssh:web:/" 'test nil nil)))))))
        (multihost-connection-test--wait request)
        (should next)
        (multihost-connection-test--wait next)
        (should (eq (multihost-request-status next) 'succeeded))))))

(ert-deftest multihost-connection-wrong-result-schema-is-rejected ()
  (multihost-connection-test--isolated
    (let* ((gate (expand-file-name "gate" multihost-state-directory))
           (marker (expand-file-name "marker" multihost-state-directory)) (callbacks 0)
           (request (multihost-connection-submit "/ssh:web:/" 'test (list :gate gate :marker marker)
                                                 (lambda (&rest _) (cl-incf callbacks)))))
      (multihost-connection-test--wait request (lambda (_) (file-exists-p marker)))
      (let ((worker (multihost-request-worker request)))
        (multihost-worker--write-json
         (multihost-connection--request-file worker "result")
         `(("schema" . 42) ("id" . ,(multihost-request-id request))
           ("result" . ,(multihost-worker--encode-value '(:status succeeded)))))
        (multihost-connection--filter
         worker (multihost-request-process request)
         (concat "MULTIHOST-RPC/1 "
                 (json-encode `(("worker" . ,(multihost-connection-worker-id worker))
                                ("kind" . "result") ("id" . ,(multihost-request-id request)))) "\n")))
      (should (eq (multihost-request-status request) 'failed))
      (should (= callbacks 1))
      (should-not (process-live-p (multihost-request-process request))))))

(ert-deftest multihost-connection-cleanup-errors-never-lose-callback-or-worker-slot ()
  (multihost-connection-test--isolated
    (let* ((gate (expand-file-name "gate" multihost-state-directory))
           (marker (expand-file-name "marker" multihost-state-directory)) (callbacks 0)
           (request (multihost-connection-submit "/ssh:web:/" 'test (list :gate gate :marker marker)
                                                 (lambda (&rest _) (cl-incf callbacks)))))
      (multihost-connection-test--wait request (lambda (_) (file-exists-p marker)))
      (cl-letf (((symbol-function 'delete-file) (lambda (&rest _) (error "Simulated file cleanup failure")))
                ((symbol-function 'delete-directory) (lambda (&rest _) (error "Simulated directory cleanup failure"))))
        (multihost-connection-cancel request))
      (should (= callbacks 1))
      (should (eq (multihost-request-status request) 'cancelled))
      (should-not (process-live-p (multihost-request-process request)))
      (should-not (multihost-connection-snapshots))
      (let ((next (multihost-connection-submit "/ssh:web:/" 'test nil nil)))
        (multihost-connection-test--wait next)
        (should (eq (multihost-request-status next) 'succeeded))))))

(ert-deftest multihost-connection-hop-keys-do-not-change-parent-tramp-proxies ()
  (multihost-connection-test--isolated
    (let ((tramp-default-proxies-alist nil))
      (should-not (equal (multihost-connection--key "/ssh:first|ssh:user@target#22:/tmp/")
                        (multihost-connection--key "/ssh:second|ssh:user@target#22:/tmp/")))
      (should-not tramp-default-proxies-alist))))

(ert-deftest multihost-connection-local-configuration-works-from-remote-buffer ()
  (multihost-connection-test--isolated
    (let* ((default-directory "/ssh:unreachable:/remote/")
           (tramp-default-proxies-alist nil)
           (request (multihost-connection-submit "/ssh:first|ssh:user@target:/tmp/" 'test nil nil)))
      ;; The handler is local-only; any real remote I/O in the parent is a bug.
      (multihost-connection-test--wait request)
      (should (eq (multihost-request-status request) 'succeeded))
      (should-not tramp-default-proxies-alist))))

(ert-deftest multihost-connection-child-prefers-source-over-stale-bytecode ()
  (multihost-connection-test--isolated
    (let ((helper (expand-file-name "multihost-test-stale.el" multihost-state-directory)))
      (with-temp-file helper
        (insert ";;; fixture -*- lexical-binding: t; -*-\n"
                "(defconst multihost-test-stale-value \"old\")\n"
                "(provide 'multihost-test-stale)\n"))
      (should (byte-compile-file helper))
      (with-temp-file helper
        (insert ";;; fixture -*- lexical-binding: t; -*-\n"
                "(defconst multihost-test-stale-value \"new\")\n"
                "(provide 'multihost-test-stale)\n"))
      ;; Make the source newer even on file systems with coarse timestamps.
      (set-file-times helper (time-add (current-time) 5))
      (with-temp-buffer
        (insert "\n")
        (prin1 `(progn
                  (add-to-list 'load-path ,multihost-state-directory)
                  (require 'multihost-test-stale)
                  (setq multihost-worker-operation-functions
                        '((test . (lambda (_payload _directory)
                                    (list :status 'succeeded :value multihost-test-stale-value))))))
               (current-buffer))
        (append-to-file (point-min) (point-max) multihost-worker-init-file))
      (let ((request (multihost-connection-submit "/ssh:web:/" 'test nil nil)))
        (multihost-connection-test--wait request)
        (should (eq (multihost-request-status request) 'succeeded))
        (should (equal (plist-get (multihost-request-result request) :value) "new"))))))

(provide 'multihost-connection-test)
;;; multihost-connection-test.el ends here
